### ISSUE TITLE
Written consent for being video recorded

### ISSUE THREAD

**Issue by lwjohnst86** [codeasmanuscript/code-along#1]
For legal purposes, anyone who teaches and is video streamed/recorded will need to add a comment to this Issue simply stating they are ok with being recorded. So something like:

> I, (name), agree to being live streamed or recorded, either video or audio, for the lesson I will be instructing.

I don't think I need anything else added here. I'll update this if it changes.

**Comment by lwjohnst86** [comment]
(Just as an example and to be safe). 

I, Luke Johnston, agree to being live streamed or recorded, either video or audio, for the lesson I will be instructing.

**Comment by zsemnani** [comment]
I, Zhila Semnani-Azad, agree to being live streamed or recorded, either video or audio, for the lesson I will be instructing.
